[dev]
  functions = "app"

[build]
  functions = "app"

[functions]
  directory = "app"
  node_bundler = "esbuild"

[[redirects]]
  from = "unkitkr.xyz/.netlify/functions/*"
  to = "unkitkr.xyz/api/:splat"
  status = 200
